### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by markitosgv** [eMAGTechLabs/messenger-mongo-bundle#20]
Hi!

Are you planning to release a new version? Current version is failing getting messages due to writeConcern flag

Thanks!

**Comment by adrianmihaila** [comment]
Hi @markitosgv,

I start to investigate this issue, and I will come to you with new updates.

Thanks,
Adi

**Comment by iosifch** [comment]
Hello! Could you provide us more context like PHP version, MongoDB version etc.?

**Comment by markitosgv** [comment]
Sorry, it was about WriteConcern but solved in recent releases
